# TODO this is incomplete.
apiVersion: v1
kind: ConfigMap
metadata:
  name: console-backend-config
  namespace: default
data:
  frontend.api-url: http://test.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-backend
  namespace: default
  labels:
    app: &app_name console-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: *app_name
  template:
    metadata:
      labels:
        app: *app_name
    spec:
      containers:
        - name: console-backend
          image: console-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              name: main-app
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: console-backend-config
                  key: database.url
            - name: REDIS_URL
---
apiVersion: v1
kind: Deployment
metadata:
  name: redis
  namespace: default
  labels:
    app-service-for: &name console-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service-for: *name
---
apiVersion: v1
kind: Service
metadata:
  name: console-frontend
  namespace: default
spec:
  selector:
    app: console-frontend
  ports:
    - protocol: TCP
      port: 443
      targetPort: main-app
  type: NodePort
