apiVersion: v1
kind: ConfigMap
metadata:
  name: console-frontend-config
  namespace: default
data:
  frontend.api-url: http://test.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-frontend
  namespace: default
  labels:
    app: &app_name console-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: *app_name
  template:
    metadata:
      labels:
        app: *app_name
    spec:
      containers:
        - name: console-frontend
          image: console-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 443
              name: main-app
          env:
            - name: REACT_APP_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: console-frontend-config
                  key: frontend.api-url
---
apiVersion: v1
kind: Service
metadata:
  name: console-frontend
  namespace: default
spec:
  selector:
    app: console-frontend
  ports:
    - protocol: TCP
      port: 443
      targetPort: main-app
  type: NodePort
