apiVersion: v1
kind: ConfigMap
metadata:
  name: console-frontend-config
data:
  frontend.api-url: http://backend.hunt-console.local # TODO use config here.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-frontend
  labels:
    {{- include "hunt-console.labels" . | nindent 4 }}
    app: &app_name console-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: *app_name
  template:
    metadata:
      labels:
        app: *app_name
    spec:
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 443
              name: main-app
          env:
            - name: REACT_APP_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: console-frontend-config
                  key: frontend.api-url
---
apiVersion: v1
kind: Service
metadata:
  name: console-frontend
spec:
  selector:
    app: console-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: main-app
  type: {{ .Values.frontend.service.type }}
